/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_facedev_js_debug_ie_IEJsDebugger */

#ifndef _Included_com_facedev_js_debug_ie_IEJsDebugger
#define _Included_com_facedev_js_debug_ie_IEJsDebugger
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_facedev_js_debug_ie_IEJsDebugger
 * Method:    getRegisteredInstancesCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_facedev_js_debug_ie_IEJsDebugger_getRegisteredInstancesCount
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
