/*
 * Provides JNI methods interfaces (generated by javah command).
 *
 *  Created on: 07.08.2012
 *      Author: alex.bereznevatiy@gmail.com
 */

#ifndef FD_JAVA_H_
#define FD_JAVA_H_




#endif /* FD_JAVA_H_ */
